# Generated by Django 5.2.8 on 2025-12-23 17:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniaAseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Compañía')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ruc', message='El RUC debe contener exactamente 13 dígitos numéricos.', regex='^\\d{13}$')], verbose_name='RUC')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contacto_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Compañía Aseguradora',
                'verbose_name_plural': 'Compañías Aseguradoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('decimal', 'Decimal'), ('entero', 'Entero'), ('texto', 'Texto')], default='texto', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('facturas', 'Facturas y Pagos'), ('polizas', 'Pólizas'), ('siniestros', 'Siniestros'), ('general', 'General')], default='general', max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['categoria', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='CorredorSeguros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Corredor')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ruc', message='El RUC debe contener exactamente 13 dígitos numéricos.', regex='^\\d{13}$')], verbose_name='RUC')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contacto_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Corredor de Seguros',
                'verbose_name_plural': 'Corredores de Seguros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Póliza')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Póliza',
                'verbose_name_plural': 'Tipos de Póliza',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('daño', 'Daño'), ('robo', 'Robo'), ('hurto', 'Hurto'), ('incendio', 'Incendio'), ('inundacion', 'Inundación'), ('terremoto', 'Terremoto'), ('vandalismo', 'Vandalismo'), ('otro', 'Otro')], max_length=50, unique=True, verbose_name='Tipo de Siniestro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Siniestro',
                'verbose_name_plural': 'Tipos de Siniestro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, unique=True, verbose_name='Número de Factura')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IVA')),
                ('contribucion_superintendencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Contribución Superintendencia (3.5%)')),
                ('contribucion_seguro_campesino', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Contribución Seguro Campesino (0.5%)')),
                ('retenciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Retenciones')),
                ('descuento_pronto_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Descuento por Pronto Pago')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('parcial', 'Pago Parcial'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado')),
                ('forma_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito')], max_length=20, verbose_name='Forma de Pago')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Número de Referencia/Comprobante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='app.factura', verbose_name='Factura')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100, unique=True, verbose_name='Número de Póliza')),
                ('suma_asegurada', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Suma Asegurada')),
                ('coberturas', models.TextField(verbose_name='Coberturas Detalladas')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio de Vigencia')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin de Vigencia')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('por_vencer', 'Por Vencer')], default='vigente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('compania_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='app.companiaaseguradora', verbose_name='Compañía Aseguradora')),
                ('corredor_seguros', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='app.corredorseguros', verbose_name='Corredor de Seguros')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tipo_poliza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='app.tipopoliza', verbose_name='Tipo de Póliza')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='app.poliza', verbose_name='Póliza'),
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siniestro', models.CharField(max_length=100, unique=True, verbose_name='Número de Siniestro')),
                ('fecha_siniestro', models.DateTimeField(verbose_name='Fecha y Hora del Siniestro')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('bien_nombre', models.CharField(max_length=200, verbose_name='Nombre del Bien')),
                ('bien_modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('bien_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('bien_marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('bien_codigo_activo', models.CharField(blank=True, max_length=100, verbose_name='Código de Activo')),
                ('responsable_custodio', models.CharField(max_length=200, verbose_name='Responsable/Custodio')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación del Siniestro')),
                ('causa', models.TextField(verbose_name='Causa del Siniestro')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Detallada')),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Estimado del Daño')),
                ('monto_indemnizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Indemnizado')),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('documentacion_pendiente', 'Documentación Pendiente'), ('enviado_aseguradora', 'Enviado a Aseguradora'), ('en_evaluacion', 'En Evaluación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('liquidado', 'Liquidado'), ('cerrado', 'Cerrado')], default='registrado', max_length=30, verbose_name='Estado')),
                ('fecha_envio_aseguradora', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío a Aseguradora')),
                ('fecha_respuesta_aseguradora', models.DateField(blank=True, null=True, verbose_name='Fecha de Respuesta de Aseguradora')),
                ('fecha_liquidacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Liquidación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='app.poliza', verbose_name='Póliza')),
                ('tipo_siniestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='app.tiposiniestro', verbose_name='Tipo de Siniestro')),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'Siniestros',
                'ordering': ['-fecha_siniestro'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('poliza', 'Póliza de Seguro'), ('factura', 'Factura'), ('comprobante_pago', 'Comprobante de Pago'), ('informe_tecnico', 'Informe Técnico'), ('denuncia', 'Denuncia'), ('proforma', 'Proforma'), ('carta_formal', 'Carta Formal'), ('fotografia', 'Fotografía'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.factura', verbose_name='Factura')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.poliza', verbose_name='Póliza')),
                ('siniestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.siniestro', verbose_name='Siniestro')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('vencimiento_poliza', 'Vencimiento de Póliza'), ('pago_pendiente', 'Pago Pendiente'), ('documentacion_pendiente', 'Documentación Pendiente'), ('respuesta_aseguradora', 'Respuesta de Aseguradora Pendiente'), ('pronto_pago', 'Descuento por Pronto Pago Disponible')], max_length=30, verbose_name='Tipo de Alerta')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('atendida', 'Atendida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('destinatarios', models.ManyToManyField(related_name='alertas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatarios')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app.factura', verbose_name='Factura')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app.poliza', verbose_name='Póliza')),
                ('siniestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app.siniestro', verbose_name='Siniestro')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='app_factura_numero__3957b1_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='app_factura_estado_b9d9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['numero_poliza'], name='app_poliza_numero__7f8b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['estado', 'fecha_fin'], name='app_poliza_estado_5bbb33_idx'),
        ),
        migrations.AddIndex(
            model_name='siniestro',
            index=models.Index(fields=['numero_siniestro'], name='app_siniest_numero__99d840_idx'),
        ),
        migrations.AddIndex(
            model_name='siniestro',
            index=models.Index(fields=['estado', 'fecha_siniestro'], name='app_siniest_estado_4e7841_idx'),
        ),
    ]
