# Generated by Django 5.2.9 on 2026-01-25 23:06


import django.db.models.deletion

from django.conf import settings

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('app', '0001_initial'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]

    operations = [

        migrations.CreateModel(

            name='ConfiguracionBackup',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('activo', models.BooleanField(default=True, verbose_name='Backup Automático Activo')),

                ('frecuencia', models.CharField(choices=[('manual', 'Manual'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=20, verbose_name='Frecuencia')),

                ('hora_ejecucion', models.TimeField(default='02:00', help_text='Hora del día para ejecutar el backup automático', verbose_name='Hora de Ejecución')),

                ('dias_retener', models.IntegerField(default=30, help_text='Número de días para mantener los backups antiguos', verbose_name='Días de Retención')),

                ('incluir_media', models.BooleanField(default=False, verbose_name='Incluir Archivos Media')),

                ('comprimir', models.BooleanField(default=True, verbose_name='Comprimir Backup')),

                ('notificar_email', models.EmailField(blank=True, help_text='Email para notificar sobre el estado de los backups', max_length=254, verbose_name='Email de Notificación')),

                ('ultimo_backup', models.DateTimeField(blank=True, null=True, verbose_name='Último Backup Exitoso')),

            ],

            options={

                'verbose_name': 'Configuración de Backup',

                'verbose_name_plural': 'Configuraciones de Backup',

            },

        ),

        migrations.CreateModel(

            name='BackupRegistro',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),

                ('ruta', models.TextField(verbose_name='Ruta del Archivo')),

                ('tamaño', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),

                ('tipo', models.CharField(choices=[('base_datos', 'Base de Datos'), ('completo', 'Completo (BD + Media)'), ('media', 'Solo Media'), ('restauracion', 'Restauración'), ('automatico', 'Automático Programado')], default='base_datos', max_length=20, verbose_name='Tipo')),

                ('estado', models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('eliminado', 'Eliminado')], default='en_progreso', max_length=20, verbose_name='Estado')),

                ('comprimido', models.BooleanField(default=False, verbose_name='Comprimido')),

                ('formato', models.CharField(default='json', max_length=10, verbose_name='Formato')),

                ('frecuencia', models.CharField(choices=[('manual', 'Manual'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='manual', max_length=20, verbose_name='Frecuencia')),

                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),

                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),

                ('notas', models.TextField(blank=True, verbose_name='Notas')),

                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de Error')),

                ('duracion_segundos', models.IntegerField(default=0, verbose_name='Duración (segundos)')),

                ('registros_respaldados', models.IntegerField(default=0, verbose_name='Registros Respaldados')),

                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),

            ],

            options={

                'verbose_name': 'Registro de Backup',

                'verbose_name_plural': 'Registros de Backups',

                'ordering': ['-fecha_creacion'],

                'indexes': [models.Index(fields=['tipo', 'estado'], name='app_backupr_tipo_6459ee_idx'), models.Index(fields=['fecha_creacion'], name='app_backupr_fecha_c_8641d2_idx')],

            },

        ),

    ]
