# Generated by Django 5.2.9 on 2025-12-26 21:55

import django.db.models.deletion
from django.db import migrations, models


def migrar_responsables_existentes(apps, schema_editor):
    """
    Migra los responsables existentes del campo CharField al nuevo modelo ResponsableCustodio.
    Crea un ResponsableCustodio por cada valor único de responsable_custodio en los siniestros.
    """
    Siniestro = apps.get_model('app', 'Siniestro')
    ResponsableCustodio = apps.get_model('app', 'ResponsableCustodio')
    
    # Obtener todos los valores únicos de responsable_custodio_old (el CharField renombrado)
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT DISTINCT responsable_custodio_old 
            FROM app_siniestro 
            WHERE responsable_custodio_old IS NOT NULL AND responsable_custodio_old != ''
        """)
        
        responsables_map = {}
        for row in cursor.fetchall():
            nombre = row[0]
            if nombre:
                # Crear o obtener el ResponsableCustodio
                responsable, created = ResponsableCustodio.objects.get_or_create(
                    nombre=nombre,
                    defaults={
                        'cargo': '',
                        'departamento': '',
                        'activo': True
                    }
                )
                responsables_map[nombre] = responsable
        
        # Actualizar todos los siniestros con el nuevo ForeignKey
        for nombre, responsable in responsables_map.items():
            cursor.execute("""
                UPDATE app_siniestro 
                SET responsable_custodio_id = %s 
                WHERE responsable_custodio_old = %s
            """, [responsable.id, nombre])


def revertir_migracion_responsables(apps, schema_editor):
    """
    Función de reversión: convierte los ForeignKey de vuelta a texto.
    """
    Siniestro = apps.get_model('app', 'Siniestro')
    ResponsableCustodio = apps.get_model('app', 'ResponsableCustodio')
    
    from django.db import connection
    with connection.cursor() as cursor:
        # Obtener todos los siniestros con responsable_custodio
        cursor.execute("""
            SELECT id, responsable_custodio_id 
            FROM app_siniestro 
            WHERE responsable_custodio_id IS NOT NULL
        """)
        
        for row in cursor.fetchall():
            siniestro_id, responsable_id = row
            try:
                responsable = ResponsableCustodio.objects.get(id=responsable_id)
                cursor.execute("""
                    UPDATE app_siniestro 
                    SET responsable_custodio_old = %s 
                    WHERE id = %s
                """, [responsable.nombre, siniestro_id])
            except ResponsableCustodio.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_documento_archivo_historicaldocumento_and_more'),
    ]

    operations = [
        # Paso 1: Crear el modelo ResponsableCustodio
        migrations.CreateModel(
            name='ResponsableCustodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(blank=True, max_length=200, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=200, verbose_name='Departamento/Área')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Responsable/Custodio',
                'verbose_name_plural': 'Responsables/Custodios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='app_respons_nombre_000e3b_idx')],
            },
        ),
        # Paso 2: Renombrar el campo CharField antiguo para preservar los datos
        migrations.RenameField(
            model_name='siniestro',
            old_name='responsable_custodio',
            new_name='responsable_custodio_old',
        ),
        # Paso 3: Agregar el nuevo campo ForeignKey (nullable temporalmente)
        migrations.AddField(
            model_name='siniestro',
            name='responsable_custodio',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='siniestros',
                to='app.responsablecustodio',
                verbose_name='Responsable/Custodio'
            ),
        ),
        # Paso 4: Migrar los datos existentes
        migrations.RunPython(migrar_responsables_existentes, revertir_migracion_responsables),
        # Paso 5: Hacer el campo requerido (no nullable)
        migrations.AlterField(
            model_name='siniestro',
            name='responsable_custodio',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='siniestros',
                to='app.responsablecustodio',
                verbose_name='Responsable/Custodio'
            ),
        ),
        # Paso 6: Eliminar el campo CharField antiguo
        migrations.RemoveField(
            model_name='siniestro',
            name='responsable_custodio_old',
        ),
        # Paso 7: Actualizar HistoricalSiniestro
        migrations.AlterField(
            model_name='historicalsiniestro',
            name='responsable_custodio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.responsablecustodio', verbose_name='Responsable/Custodio'),
        ),
    ]
