# Generated by Django 5.2.9 on 2026-01-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_configuracionbackup_backupregistro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepolizaramo',
            options={'ordering': ['poliza', 'subgrupo_ramo__nombre'], 'verbose_name': 'Detalle de Póliza por Ramo', 'verbose_name_plural': 'Detalles de Póliza por Ramo'},
        ),
        migrations.RemoveIndex(
            model_name='detallepolizaramo',
            name='app_detalle_poliza__0396e1_idx',
        ),
        migrations.RemoveField(
            model_name='detallepolizaramo',
            name='documento_contable',
        ),
        migrations.RemoveField(
            model_name='detallepolizaramo',
            name='grupo_ramo',
        ),
        migrations.RemoveField(
            model_name='detallepolizaramo',
            name='numero_factura',
        ),
        migrations.RemoveField(
            model_name='historicaldetallepolizaramo',
            name='documento_contable',
        ),
        migrations.RemoveField(
            model_name='historicaldetallepolizaramo',
            name='grupo_ramo',
        ),
        migrations.RemoveField(
            model_name='historicaldetallepolizaramo',
            name='numero_factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='documento_contable',
            field=models.CharField(blank=True, help_text='Código del documento contable asociado', max_length=100, verbose_name='Documento Contable'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó el pago completo', null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='documento_contable',
            field=models.CharField(blank=True, help_text='Código del documento contable asociado', max_length=100, verbose_name='Documento Contable'),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó el pago completo', null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='conforme_indemnizacion',
            field=models.BooleanField(default=False, help_text='Indica si UTPL está de acuerdo con el monto propuesto', verbose_name='Conforme con Indemnización'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='email_origen_recibo',
            field=models.CharField(blank=True, help_text='Dirección de email de donde se recibió el recibo', max_length=255, verbose_name='Email Origen'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='email_respuesta_broker',
            field=models.CharField(blank=True, help_text='Email de donde llegó la respuesta del broker', max_length=255, verbose_name='Email Respuesta Broker'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='en_disputa',
            field=models.BooleanField(default=False, verbose_name='En Disputa'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='fecha_disputa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Disputa'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='fecha_envio_liquidacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se envió el recibo firmado. Inicia las 72h hábiles.', null=True, verbose_name='Fecha Envío a Liquidación'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='fecha_limite_liquidacion',
            field=models.DateTimeField(blank=True, help_text='72 horas hábiles desde el envío', null=True, verbose_name='Fecha Límite Liquidación'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='fecha_recibo_recibido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Recepción Recibo'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='fecha_respuesta_broker',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta del Broker'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='monto_liquidado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente depositado por la aseguradora', max_digits=15, null=True, verbose_name='Monto Liquidado'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='motivo_diferencia_monto',
            field=models.TextField(blank=True, help_text='Explicación si el monto liquidado difiere del aprobado', verbose_name='Motivo Diferencia de Monto'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='motivo_disputa',
            field=models.TextField(blank=True, help_text='Razón por la cual no se acepta el recibo', verbose_name='Motivo de Disputa'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='notificacion_72h_enviada',
            field=models.BooleanField(default=False, help_text='Se envió recordatorio por vencimiento de plazo', verbose_name='Notificación 72h Enviada'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='Referencia de la transferencia o pago', max_length=100, verbose_name='Número de Comprobante'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='recibo_firmado',
            field=models.TextField(blank=True, help_text='PDF del recibo firmado por UTPL', max_length=100, null=True, verbose_name='Recibo Firmado'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='recibo_indemnizacion',
            field=models.TextField(blank=True, help_text='PDF del recibo enviado por la aseguradora', max_length=100, null=True, verbose_name='Recibo de Indemnización'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='resolucion_disputa',
            field=models.TextField(blank=True, help_text='Cómo se resolvió la disputa', verbose_name='Resolución de Disputa'),
        ),
        migrations.AddField(
            model_name='historicalsiniestro',
            name='subramo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subramo del siniestro (debe pertenecer a la póliza)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.subgruporamo', verbose_name='Subramo'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='conforme_indemnizacion',
            field=models.BooleanField(default=False, help_text='Indica si UTPL está de acuerdo con el monto propuesto', verbose_name='Conforme con Indemnización'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='email_origen_recibo',
            field=models.CharField(blank=True, help_text='Dirección de email de donde se recibió el recibo', max_length=255, verbose_name='Email Origen'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='email_respuesta_broker',
            field=models.CharField(blank=True, help_text='Email de donde llegó la respuesta del broker', max_length=255, verbose_name='Email Respuesta Broker'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='en_disputa',
            field=models.BooleanField(default=False, verbose_name='En Disputa'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_disputa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Disputa'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_envio_liquidacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se envió el recibo firmado. Inicia las 72h hábiles.', null=True, verbose_name='Fecha Envío a Liquidación'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_limite_liquidacion',
            field=models.DateTimeField(blank=True, help_text='72 horas hábiles desde el envío', null=True, verbose_name='Fecha Límite Liquidación'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_recibo_recibido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Recepción Recibo'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_respuesta_broker',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta del Broker'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='monto_liquidado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente depositado por la aseguradora', max_digits=15, null=True, verbose_name='Monto Liquidado'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='motivo_diferencia_monto',
            field=models.TextField(blank=True, help_text='Explicación si el monto liquidado difiere del aprobado', verbose_name='Motivo Diferencia de Monto'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='motivo_disputa',
            field=models.TextField(blank=True, help_text='Razón por la cual no se acepta el recibo', verbose_name='Motivo de Disputa'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='notificacion_72h_enviada',
            field=models.BooleanField(default=False, help_text='Se envió recordatorio por vencimiento de plazo', verbose_name='Notificación 72h Enviada'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='Referencia de la transferencia o pago', max_length=100, verbose_name='Número de Comprobante'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='recibo_firmado',
            field=models.FileField(blank=True, help_text='PDF del recibo firmado por UTPL', null=True, upload_to='siniestros/recibos_firmados/%Y/%m/', verbose_name='Recibo Firmado'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='recibo_indemnizacion',
            field=models.FileField(blank=True, help_text='PDF del recibo enviado por la aseguradora', null=True, upload_to='siniestros/recibos/%Y/%m/', verbose_name='Recibo de Indemnización'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='resolucion_disputa',
            field=models.TextField(blank=True, help_text='Cómo se resolvió la disputa', verbose_name='Resolución de Disputa'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='subramo',
            field=models.ForeignKey(blank=True, help_text='Subramo del siniestro (debe pertenecer a la póliza)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='app.subgruporamo', verbose_name='Subramo'),
        ),
        migrations.AlterField(
            model_name='detallepolizaramo',
            name='subgrupo_ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_poliza', to='app.subgruporamo', verbose_name='Subgrupo de Ramo'),
        ),
        migrations.AlterField(
            model_name='historicalsiniestro',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('notificado_broker', 'Notificado al Broker'), ('documentacion_lista', 'Documentación Lista'), ('enviado_aseguradora', 'Enviado a Aseguradora'), ('recibo_recibido', 'Recibo Recibido'), ('en_disputa', 'En Disputa'), ('recibo_firmado', 'Recibo Firmado'), ('pendiente_liquidacion', 'Pendiente Liquidación'), ('vencido', 'Vencido (72h)'), ('liquidado', 'Liquidado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado'), ('rechazado', 'Rechazado')], default='registrado', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalsiniestro',
            name='tipo_siniestro',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Campo legacy - usar subramo en su lugar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.tiposiniestro', verbose_name='Tipo de Siniestro'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('notificado_broker', 'Notificado al Broker'), ('documentacion_lista', 'Documentación Lista'), ('enviado_aseguradora', 'Enviado a Aseguradora'), ('recibo_recibido', 'Recibo Recibido'), ('en_disputa', 'En Disputa'), ('recibo_firmado', 'Recibo Firmado'), ('pendiente_liquidacion', 'Pendiente Liquidación'), ('vencido', 'Vencido (72h)'), ('liquidado', 'Liquidado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado'), ('rechazado', 'Rechazado')], default='registrado', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='tipo_siniestro',
            field=models.ForeignKey(blank=True, help_text='Campo legacy - usar subramo en su lugar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='app.tiposiniestro', verbose_name='Tipo de Siniestro'),
        ),
        migrations.AddIndex(
            model_name='detallepolizaramo',
            index=models.Index(fields=['poliza', 'subgrupo_ramo'], name='app_detalle_poliza__4864ea_idx'),
        ),
    ]
