# Generated by Django 5.2.9 on 2026-01-19 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_ramos_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntosiniestro',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_vinculados', to='app.checklistsiniestro', verbose_name='Item del Checklist'),
        ),
    ]
