# Generated by Django 5.2.9 on 2026-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_checklist_item_to_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiaaseguradora',
            name='brokers',
            field=models.ManyToManyField(blank=True, help_text='Listado de brokers con convenio para esta aseguradora.', related_name='companias_aseguradas', to='app.corredorseguros', verbose_name='Brokers autorizados'),
        ),
    ]
